### ISSUE TITLE
Package review

### ISSUE THREAD

**Issue by ahcorde** [ros-visualization/tango_icons_vendor#2]
This package was never reviewed. I would suggest and comment some possible improvements.

 - The maintainer of this pacakge is @dirk-thomas but I have not seen any commits or PRs from him, is he aware?
 -  The version of this package is `1.0.0` but this packages was never released, I supposed that this should be changed to `0.0.0`.
 - Icons are copied in the repository. Does make sense to download from the [offical link](http://tango.freedesktop.org/releases/tango-icon-theme-0.8.90.tar.gz)?
- Does the name of the package should contain `vendor`?

@dirk-thomas and @brawner . I appreciate your thoughts, then I will follow up with PRs

**Comment by dirk-thomas** [comment]
> The maintainer of this pacakge is @dirk-thomas but I have not seen any commits or PRs from him, is he aware?

No, please change the maintainer to someone else.

>  The version of this package is `1.0.0` but this packages was never released, I supposed that this should be changed to `0.0.0`.

Yes, 0.0.0.

> Does the name of the package should contain `vendor`?

The package name shouldn't include `qt_gui` since the icons have nothing to do with it. They can be used in any other context. Maybe a name like `tango_icons_vendor`?

---

The web links in the package description in the manifest file don't work for me.

**Comment by ahcorde** [comment]
- Version https://github.com/ros-visualization/qt_gui_icons/pull/3
 - Renamed https://github.com/ros-visualization/qt_gui_icons/pull/4 (also the repository name)
 - Maintainer https://github.com/ros-visualization/qt_gui_icons/pull/5
 - Description links: https://github.com/ros-visualization/tango_icons_vendor/pull/6

**Comment by ahcorde** [comment]
this package has been reviewed, closing this issue.
